package com.example.taskmanagementapp.constant

import com.example.taskmanagementapp.R


val listBoarSticker = listOf(
    R.drawable.boar_emoji_amazed,
    R.drawable.boar_emoji_angry,
    R.drawable.boar_emoji_annoyed,
    R.drawable.boar_emoji_confused,
    R.drawable.boar_emoji_cool,
    R.drawable.boar_emoji_dizzy,
    R.drawable.boar_emoji_hi,
    R.drawable.boar_emoji_lol,
    R.drawable.boar_emoji_love,
    R.drawable.boar_emoji_pissed,
    R.drawable.boar_emoji_puke,
    R.drawable.boar_emoji_sad,
    R.drawable.boar_emoji_scared,
    R.drawable.boar_emoji_shocked,
    R.drawable.boar_emoji_shy,
    R.drawable.boar_emoji_sick,
    R.drawable.boar_emoji_sleep,
    R.drawable.boar_emoji_smile,
    R.drawable.boar_emoji_smirk,
    R.drawable.boar_emoji_yawn,
)
val listBunnySticker = listOf(
    R.drawable.bunny_emoji_amazed,
    R.drawable.bunny_emoji_angry,
    R.drawable.bunny_emoji_annoyed,
    R.drawable.bunny_emoji_confused,
    R.drawable.bunny_emoji_cool,
    R.drawable.bunny_emoji_dizzy,
    R.drawable.bunny_emoji_hi,
    R.drawable.bunny_emoji_lol,
    R.drawable.bunny_emoji_love,
    R.drawable.bunny_emoji_pissed,
    R.drawable.bunny_emoji_puke,
    R.drawable.bunny_emoji_sad,
    R.drawable.bunny_emoji_scared,
    R.drawable.bunny_emoji_shocked,
    R.drawable.bunny_emoji_shy,
    R.drawable.bunny_emoji_sick,
    R.drawable.bunny_emoji_sleep,
    R.drawable.bunny_emoji_smile,
    R.drawable.bunny_emoji_smirk,
    R.drawable.bunny_emoji_yawn,
)
val listTaskType = listOf(
    R.drawable.ic_ban,
    R.drawable.ic_running_man,
    R.drawable.ic_bag,
    R.drawable.ic_pet,
    R.drawable.ic_pet_walking,
)

val listBreakfast = listOf(
    R.drawable.apple,
    R.drawable.apron,
    R.drawable.bread,
    R.drawable.butter,
    R.drawable.cake,
    R.drawable.cereals,
    R.drawable.cheese,
    R.drawable.coffee_bean,
    R.drawable.coffee,
    R.drawable.cookie,
    R.drawable.croissant,
    R.drawable.cupcake,
    R.drawable.donut,
    R.drawable.fried_egg,
    R.drawable.honey,
    R.drawable.hot_drink,
    R.drawable.jam,
    R.drawable.juice,
    R.drawable.microwave_oven,
    R.drawable.milk,
    R.drawable.orange_juice,
    R.drawable.pancake,
    R.drawable.pastry,
    R.drawable.sandwich,
    R.drawable.sausage,
    R.drawable.sugar,
    R.drawable.tea,
    R.drawable.toaster,
)
val listSticker = listOf(
    R.drawable.holidays_1,
    R.drawable.holidays_2,
    R.drawable.holidays_3,
    R.drawable.holidays_4,
    R.drawable.holidays_5,
    R.drawable.holidays_6,
    R.drawable.holidays_7,
    R.drawable.holidays_8,
    R.drawable.holidays_9,
    R.drawable.holidays_10,
    R.drawable.holidays_11,
    R.drawable.holidays_12,
    R.drawable.holidays_13,
    R.drawable.holidays_14,
    R.drawable.holidays_15,
    R.drawable.holidays_16,
    R.drawable.holidays_17,
    R.drawable.holidays_18,
    R.drawable.holidays_19,
    R.drawable.holidays_20,
)
